inherit_from: .rubocop_todo.yml

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/EmptyLines:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
