AllCops:
  TargetRubyVersion: 2.1

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Naming/VariableNumber:
  EnforcedStyle: snake_case

# Helps with readability
Layout/EmptyLines:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Helps with readability
Layout/CaseIndentation:
  Enabled: false

# The test code is safe to evaluate
Security/Eval:
  Exclude:
    - 'testing/**/*'

Metrics/BlockLength:
  Exclude:
    # RSpec tests are inherently large blocks of code
    - 'testing/rspec/spec/**/*_spec.rb'
    # Gemspecs are inherently one large block of code
    - cuke_linter.gemspec

# Whitespace improves readability
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EndOfLine:
  Exclude:
    # Git isn't changing the line endings locally for some reason
    - 'bin/console'

# Documentation is checked using RDoc
Style/Documentation:
  Enabled: false
