inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

# RuboCop does not support as old a Ruby version as this gem does
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Naming/VariableNumber:
  EnforcedStyle: snake_case

# Helps with readability
Layout/EmptyLines:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Helps with readability
Layout/CaseIndentation:
  Enabled: false
