os:
  - linux
  - osx
sudo: false

# JRuby isn't working on the new default distribution
dist: trusty

language: ruby
rvm:
  - 2.3.1
  - 2.4.0
  - 2.5.1
  - 2.6.0
  - jruby-9.1.7.0


gemfile:
  - testing/gemfiles/cuke_modeler1.gemfile
  - testing/gemfiles/cuke_modeler2.gemfile

before_install: gem install bundler -v 1.16.2

script: bundle exec rake cuke_linter:ci_build
