os:
  - linux
  - osx
sudo: false

# JRuby isn't working on the new default distribution
dist: trusty

language: ruby
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.1
  - 2.6.0
  - jruby-9.1.7.0

matrix:
  exclude:
    # Ruby 2.3.x is currently broken on TravisCI and is no longer a supported Ruby version, anyway.
    - rvm: 2.3.3
      os: osx

gemfile:
  - testing/gemfiles/cuke_modeler1.gemfile
  - testing/gemfiles/cuke_modeler2.gemfile

gemfile:
  - testing/gemfiles/cuke_modeler1.gemfile
  - testing/gemfiles/cuke_modeler2.gemfile

before_install: gem install bundler -v 1.16.2

script: bundle exec rake cuke_linter:ci_build
